//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.34014
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VWFCalc.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VWFCalc.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Anzeigen ähnelt.
        /// </summary>
        internal static string Anzeigen_DE {
            get {
                return ResourceManager.GetString("Anzeigen_DE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show ähnelt.
        /// </summary>
        internal static string Anzeigen_EN {
            get {
                return ResourceManager.GetString("Anzeigen_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap applications_engineering {
            get {
                object obj = ResourceManager.GetObject("applications_engineering", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Beenden ähnelt.
        /// </summary>
        internal static string Beenden_DE {
            get {
                return ResourceManager.GetString("Beenden_DE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Exit ähnelt.
        /// </summary>
        internal static string Beenden_EN {
            get {
                return ResourceManager.GetString("Beenden_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kritische Zeilenlänge: ähnelt.
        /// </summary>
        internal static string CritZeilenlaenge_DE {
            get {
                return ResourceManager.GetString("CritZeilenlaenge_DE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Critical length of line: ähnelt.
        /// </summary>
        internal static string CritZeilenlaenge_EN {
            get {
                return ResourceManager.GetString("CritZeilenlaenge_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Datei ähnelt.
        /// </summary>
        internal static string Datei_DE {
            get {
                return ResourceManager.GetString("Datei_DE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die File ähnelt.
        /// </summary>
        internal static string Datei_EN {
            get {
                return ResourceManager.GetString("Datei_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DSC01074 {
            get {
                object obj = ResourceManager.GetObject("DSC01074", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Laden ähnelt.
        /// </summary>
        internal static string EditorLoad_DE {
            get {
                return ResourceManager.GetString("EditorLoad_DE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Load ähnelt.
        /// </summary>
        internal static string EditorLoad_EN {
            get {
                return ResourceManager.GetString("EditorLoad_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Neues Table ähnelt.
        /// </summary>
        internal static string EditorNew_DE {
            get {
                return ResourceManager.GetString("EditorNew_DE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die New Table ähnelt.
        /// </summary>
        internal static string EditorNew_EN {
            get {
                return ResourceManager.GetString("EditorNew_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Speichern ähnelt.
        /// </summary>
        internal static string EditorSave_DE {
            get {
                return ResourceManager.GetString("EditorSave_DE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save ähnelt.
        /// </summary>
        internal static string EditorSave_EN {
            get {
                return ResourceManager.GetString("EditorSave_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap go_down {
            get {
                object obj = ResourceManager.GetObject("go_down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap go_up {
            get {
                object obj = ResourceManager.GetObject("go_up", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bei Textlängenermittlung zu ignorierende Zeichengruppen (eine pro Zeile): ähnelt.
        /// </summary>
        internal static string IgnoriereZeichengruppen_DE {
            get {
                return ResourceManager.GetString("IgnoriereZeichengruppen_DE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ignore following groups while getting textlength (one per line): ähnelt.
        /// </summary>
        internal static string IgnoriereZeichengruppen_EN {
            get {
                return ResourceManager.GetString("IgnoriereZeichengruppen_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Info ähnelt.
        /// </summary>
        internal static string Info_DE {
            get {
                return ResourceManager.GetString("Info_DE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die About ähnelt.
        /// </summary>
        internal static string Info_EN {
            get {
                return ResourceManager.GetString("Info_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hintergrundfarbe Textfeld ähnelt.
        /// </summary>
        internal static string KonfigBackcol_DE {
            get {
                return ResourceManager.GetString("KonfigBackcol_DE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Color background ähnelt.
        /// </summary>
        internal static string KonfigBackcol_EN {
            get {
                return ResourceManager.GetString("KonfigBackcol_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Textfarbe kritische Länge ähnelt.
        /// </summary>
        internal static string KonfigCritText_DE {
            get {
                return ResourceManager.GetString("KonfigCritText_DE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Color critical length ähnelt.
        /// </summary>
        internal static string KonfigCritText_EN {
            get {
                return ResourceManager.GetString("KonfigCritText_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Farben ähnelt.
        /// </summary>
        internal static string KonfigFarben_DE {
            get {
                return ResourceManager.GetString("KonfigFarben_DE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Colors ähnelt.
        /// </summary>
        internal static string KonfigFarben_EN {
            get {
                return ResourceManager.GetString("KonfigFarben_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ingoriere Leerzeichen an Zeilenende ähnelt.
        /// </summary>
        internal static string KonfigIgnoreSpace_DE {
            get {
                return ResourceManager.GetString("KonfigIgnoreSpace_DE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ignore space at end of line ähnelt.
        /// </summary>
        internal static string KonfigIgnoreSpace_EN {
            get {
                return ResourceManager.GetString("KonfigIgnoreSpace_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zu ignorierende Zeilenanfänge: ähnelt.
        /// </summary>
        internal static string KonfigIgnoreZeilenbeginn_DE {
            get {
                return ResourceManager.GetString("KonfigIgnoreZeilenbeginn_DE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ignore lines starting with following chars: ähnelt.
        /// </summary>
        internal static string KonfigIgnoreZeilenbeginn_EN {
            get {
                return ResourceManager.GetString("KonfigIgnoreZeilenbeginn_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Textfarbe Überlänge ähnelt.
        /// </summary>
        internal static string KonfigMaxText_DE {
            get {
                return ResourceManager.GetString("KonfigMaxText_DE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Color overlong length ähnelt.
        /// </summary>
        internal static string KonfigMaxText_EN {
            get {
                return ResourceManager.GetString("KonfigMaxText_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Textfarbe Unterlänge ähnelt.
        /// </summary>
        internal static string KonfigMinText_DE {
            get {
                return ResourceManager.GetString("KonfigMinText_DE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Textcolor unterlength ähnelt.
        /// </summary>
        internal static string KonfigMinText_EN {
            get {
                return ResourceManager.GetString("KonfigMinText_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Textfarbe normaler Text ähnelt.
        /// </summary>
        internal static string KonfigNormText_DE {
            get {
                return ResourceManager.GetString("KonfigNormText_DE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Color normal text ähnelt.
        /// </summary>
        internal static string KonfigNormText_EN {
            get {
                return ResourceManager.GetString("KonfigNormText_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sonstiges ähnelt.
        /// </summary>
        internal static string KonfigSonstiges_DE {
            get {
                return ResourceManager.GetString("KonfigSonstiges_DE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Miscellaneous ähnelt.
        /// </summary>
        internal static string KonfigSonstiges_EN {
            get {
                return ResourceManager.GetString("KonfigSonstiges_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Konfiguration ähnelt.
        /// </summary>
        internal static string Konfiguration_DE {
            get {
                return ResourceManager.GetString("Konfiguration_DE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Configuration ähnelt.
        /// </summary>
        internal static string Konfiguration_EN {
            get {
                return ResourceManager.GetString("Konfiguration_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Leerzeilen einblenden: ähnelt.
        /// </summary>
        internal static string LeerzeilenZeigen_DE {
            get {
                return ResourceManager.GetString("LeerzeilenZeigen_DE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show empty lines: ähnelt.
        /// </summary>
        internal static string LeerzeilenZeigen_EN {
            get {
                return ResourceManager.GetString("LeerzeilenZeigen_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Maximale Zeilenlänge in Pixeln: ähnelt.
        /// </summary>
        internal static string MaxZeilenlaenge_DE {
            get {
                return ResourceManager.GetString("MaxZeilenlaenge_DE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Maximum pixelcount per line: ähnelt.
        /// </summary>
        internal static string MaxZeilenlaenge_EN {
            get {
                return ResourceManager.GetString("MaxZeilenlaenge_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Minimale Zeilenlänge: ähnelt.
        /// </summary>
        internal static string MinZeilenlaenge_DE {
            get {
                return ResourceManager.GetString("MinZeilenlaenge_DE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Minimum pixelcount per line: ähnelt.
        /// </summary>
        internal static string MinZeilenlaenge_EN {
            get {
                return ResourceManager.GetString("MinZeilenlaenge_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Pixel zwischen Buchstaben: ähnelt.
        /// </summary>
        internal static string PixelBetween_DE {
            get {
                return ResourceManager.GetString("PixelBetween_DE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Pixels between characters: ähnelt.
        /// </summary>
        internal static string PixelBetween_EN {
            get {
                return ResourceManager.GetString("PixelBetween_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Pixelzahl markierter Text: ähnelt.
        /// </summary>
        internal static string PixelzahlMarkiert_DE {
            get {
                return ResourceManager.GetString("PixelzahlMarkiert_DE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Pixelcount selected text: ähnelt.
        /// </summary>
        internal static string PixelzahlMarkiert_EN {
            get {
                return ResourceManager.GetString("PixelzahlMarkiert_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Projekt öffnen ähnelt.
        /// </summary>
        internal static string ProjektLaden_DE {
            get {
                return ResourceManager.GetString("ProjektLaden_DE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Open project ähnelt.
        /// </summary>
        internal static string ProjektLaden_EN {
            get {
                return ResourceManager.GetString("ProjektLaden_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Projekt speichern ähnelt.
        /// </summary>
        internal static string ProjektSpeichern_DE {
            get {
                return ResourceManager.GetString("ProjektSpeichern_DE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save project ähnelt.
        /// </summary>
        internal static string ProjektSpeichern_EN {
            get {
                return ResourceManager.GetString("ProjektSpeichern_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Projekt speichern unter... ähnelt.
        /// </summary>
        internal static string ProjektSpeichernAls_DE {
            get {
                return ResourceManager.GetString("ProjektSpeichernAls_DE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save project as... ähnelt.
        /// </summary>
        internal static string ProjektSpeichernAls_EN {
            get {
                return ResourceManager.GetString("ProjektSpeichernAls_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Speichern ähnelt.
        /// </summary>
        internal static string SpeichereTextdatei_DE {
            get {
                return ResourceManager.GetString("SpeichereTextdatei_DE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save ähnelt.
        /// </summary>
        internal static string SpeichereTextdatei_EN {
            get {
                return ResourceManager.GetString("SpeichereTextdatei_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sprache: ähnelt.
        /// </summary>
        internal static string Sprache_DE {
            get {
                return ResourceManager.GetString("Sprache_DE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Language: ähnelt.
        /// </summary>
        internal static string Sprache_EN {
            get {
                return ResourceManager.GetString("Sprache_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Table-Editor ähnelt.
        /// </summary>
        internal static string TableEditor_DE {
            get {
                return ResourceManager.GetString("TableEditor_DE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Table-Editor ähnelt.
        /// </summary>
        internal static string TableEditor_EN {
            get {
                return ResourceManager.GetString("TableEditor_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Table laden ähnelt.
        /// </summary>
        internal static string TableLaden_DE {
            get {
                return ResourceManager.GetString("TableLaden_DE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Load Table ähnelt.
        /// </summary>
        internal static string TableLaden_EN {
            get {
                return ResourceManager.GetString("TableLaden_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fehler beim Einlesen des Tables. Ist die geladene Datei ein korrektes Table? ähnelt.
        /// </summary>
        internal static string TableLadenFehler_DE {
            get {
                return ResourceManager.GetString("TableLadenFehler_DE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error while loading table. Is the file a correct table file? ähnelt.
        /// </summary>
        internal static string TableLadenFehler_EN {
            get {
                return ResourceManager.GetString("TableLadenFehler_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Textdatei laden ähnelt.
        /// </summary>
        internal static string TextdateiLaden_DE {
            get {
                return ResourceManager.GetString("TextdateiLaden_DE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Load Textfile ähnelt.
        /// </summary>
        internal static string TextdateiLaden_EN {
            get {
                return ResourceManager.GetString("TextdateiLaden_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Übrige Pixel: ähnelt.
        /// </summary>
        internal static string UebrigePixel_DE {
            get {
                return ResourceManager.GetString("UebrigePixel_DE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Pixels left: ähnelt.
        /// </summary>
        internal static string UebrigePixel_EN {
            get {
                return ResourceManager.GetString("UebrigePixel_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Werkzeuge ähnelt.
        /// </summary>
        internal static string Werkzeuge_DE {
            get {
                return ResourceManager.GetString("Werkzeuge_DE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tools ähnelt.
        /// </summary>
        internal static string Werkzeuge_EN {
            get {
                return ResourceManager.GetString("Werkzeuge_EN", resourceCulture);
            }
        }
    }
}
